# Generated by Django 3.2.5 on 2022-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intrest',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
